<a href="https://colab.research.google.com/github/MyrewinGrepo/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np

A=([[1,2,3,],
   [4,5,6]])
B=([[1,2],
    [3,4],
    [5,6]])
C=([[1,2,3],
    [4,5,6],
    [7,8,9]])
D=([[1,2],
    [3,4]])

AB=np.dot(A,B)
print("a.\n",AB)
Z=np.add(D,D)
print("b.\n",Z)
S=np.array([2])
V=S*C
print("c.\n",V)


a.
 [[22 28]
 [49 64]]
b.
 [[2 4]
 [6 8]]
c.
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [40]:
import numpy as np

A=([2,7,4])
B=([3,9,8])
cross_product=np.cross(A,B)
print("Cross-Produt of A and B:", cross_product)

Cross-Produt of A and B: [20 -4 -3]
