<a href="https://colab.research.google.com/github/MyrewinGrepo/58013-Linear-Algebra/blob/main/Practical_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question1

In [2]:
import numpy as np

z=np.array([[1,2,3,4,5,6,7,8,9,10],
            [2,4,6,8,10,12,14,16,18,20],
            [3,6,9,12,15,18,21,24,17,30],
            [4,8,12,16,20,24,28,32,36,40],
            [5,10,15,20,25,30,35,40,45,50],
            [6,12,18,24,30,36,42,48,54.60],
            [7,14,21,28,35,42,49,56,63,70],
            [8,16,24,32,40,48,56,64,72,80],
            [9,18,27,36,45,54,63,72,81,90],
            [10,20,30,40,50,60,70,80,90,100]])
print(z)

[list([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
 list([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
 list([3, 6, 9, 12, 15, 18, 21, 24, 17, 30])
 list([4, 8, 12, 16, 20, 24, 28, 32, 36, 40])
 list([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
 list([6, 12, 18, 24, 30, 36, 42, 48, 54.6])
 list([7, 14, 21, 28, 35, 42, 49, 56, 63, 70])
 list([8, 16, 24, 32, 40, 48, 56, 64, 72, 80])
 list([9, 18, 27, 36, 45, 54, 63, 72, 81, 90])
 list([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])] 0


<ipython-input-2-193710ec95c2>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  z=np.array([[1,2,3,4,5,6,7,8,9,10],


#Question 2

In [9]:
squared=np.squared(z)
print(squared)

AttributeError: ignored

#Question 3



In [ ]:
import numpy as np

c=np.eye(3,3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 4

In [4]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("size:",np.size(matrix))
print("shape:",np.shape(matrix))
print("dimension:",np.ndim(matrix))




size: 12
shape: (3, 4)
dimension: 2


#Question5

In [8]:
import numpy as np

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

result_array = arrayOne + arrayTwo
result_array_squared = np.square(result_array)

print(result_array)

print(result_array_squared)


[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]
