<a href="https://colab.research.google.com/github/MyrewinGrepo/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
#Commutative
C = np.array([
    [5,4,1],
    [4,2,3],
    [9,0,3]
])
D = np.array([
    [5,2,1],
    [3,6,9],
    [7,8,4]
])
print(np.dot(C,D))
print(np.dot(D,C))

[[44 42 45]
 [47 44 34]
 [66 42 21]]
[[ 42  24  14]
 [120  24  48]
 [103  44  43]]


In [ ]:
#Associative
E = np.array([
    [9,4,3],
    [8,5,2],
    [7,6,1]
])
F = np.array([
    [5,0,7],
    [8,5,2],
    [6,1,9]
])
G = np.array([
    [1,6,0],
    [2,5,9],
    [3,7,8]
])
print(np.dot(E, np.dot(F,G)))
print(np.dot(np.dot(E,F), G))

[[ 435 1371  991]
 [ 398 1275  915]
 [ 361 1179  839]]
[[ 435 1371  991]
 [ 398 1275  915]
 [ 361 1179  839]]


In [ ]:
#Identity
K = np.array([
    [2,4,2],
    [4,8,1],
    [8,3,6]
])
L = np.array([
    [5,8,9],
    [1,6,1],
    [8,7,5]
])
print(np.dot(K,L))

[[ 30  54  32]
 [ 36  87  49]
 [ 91 124 105]]


In [ ]:
#Distributive
H = np.array([
    [1,0,6],
    [1,2,4],
    [9,4,8]
])
I = np.array([
    [6,2,0],
    [8,6,2],
    [3,9,2]
])
J = np.array([
    [2,4,8],
    [3,2,9],
    [8,9,1]
])
print(np.add(H, np.dot(I,J)))
print(np.add(np.dot(H,I), J))

[[ 19  28  72]
 [ 51  64 124]
 [ 58  52 115]]
[[ 26  60  20]
 [ 37  52  21]
 [118 123  25]]


In [ ]:
#Zero
M = np.array([
    [2,5,6],
    [3,0,6],
    [8,6,3]
])
N = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
print(np.dot(M,N))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#Dimension
O = np.array([
    [1,0,7],
    [3,6,1]
])
P = np.array([
    [3,1,],
    [1,2,],
    [6,3,]
])
print(np.dot(O,P))
print(np.dot(P,O))


[[45 22]
 [21 18]]
[[ 6  6 22]
 [ 7 12  9]
 [15 18 45]]
