<a href="https://colab.research.google.com/github/MyrewinGrepo/58013-Linear-Algebra/blob/main/Python_Exercise_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##Python codes to declare a matrix
import numpy as np
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(A)

A=np.array([[1,2],[4,7]])
B=(np.linalg.inv(A))
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-7.  2.]
 [ 4. -1.]]


In [2]:
import numpy as np
A = np.array([[1,2],[4,7]])
invA = (np.linalg.inv(A))
print(invA)


[[-7.  2.]
 [ 4. -1.]]


In [3]:
#Python Program to Transpose a 4x4 Matrix A=([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print(A)
B=(np.transpose(A))
print(B)


[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
