<a href="https://colab.research.google.com/github/MyrewinGrepo/58013-Linear-Algebra/blob/main/Vector_Space_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ',A)
print('Vector B is ',B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


#Shape of Py

In [ ]:
import numpy as np
###Checking shapes
### Shapes tells us how many rows and columns are there
ball1 =np.array([1,2,3])
ball2 =np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls
print(z)


[1 2 3]
[ 0  1 -1]
(3, 3)


#Addition

In [ ]:
import numpy as np
A=np.array([4,3,])
B=np.array([2,-5,])
R=np.add(A,B)
print(R)

[ 6 -2]


In [ ]:
R1=np.subtract(A,B)
print(R1)
R2=np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


In [60]:
S=np.array([2])
V=S*A
print(V)

[8 6]


In [82]:
A=np.array([4,3])
B=np.array([[2],[-5]])
Z=A*B
print(Z)
t=np.transpose(Z)
print(t)

[[  8   6]
 [-20 -15]]
[[  8 -20]
 [  6 -15]]


In [83]:
c=np.eye(3,3)
print(c)

d= np.zeros([5,5])
print(d)
e=np.full((3,3),7)
print(e)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
